### ISSUE TITLE
Breakfast Recipe Issue

### ISSUE THREAD

**Issue by msastry-code** [IntroToCode/Spring21_Recipes_Codemates7#11]
## 💬 Discussion topic

We need a savory breakfast option. Currently, all options are too sweet!

## ❗ Potential issues

Savory options might have conflicting dietary limits for people!

## 👥 People to consult

@alejandravl 

## 📃 Details

Text

**Comment by alejandravl** [comment]
No worries @msastry-code , I'll add pancakes!
