### ISSUE TITLE
Dinner Issue: More Pork Please!

### ISSUE THREAD

**Issue by gitjl22** [IntroToCode/Spring21_Recipes_Codemates7#12]
## 💬 Discussion topic

Is 1 pound enough meat? Maybe we should use 1.5 pounds?

## ❗ Potential issues

Not sure we have enough meat in there, people will still be hungry.

## 👥 People to consult

@gitjl22
@g7lewis
@arontheising
@alejandravl
@msastry-code

## 📃 Details

Just pick something to get started

**Comment by alejandravl** [comment]
some hungry folks here, I'll add more pork! @gitjl22
