### ISSUE TITLE
Breakfast recipe seems more like dinner

### ISSUE THREAD

**Issue by alejandravl** [IntroToCode/Spring21_Recipes_Codemates7#13]
## 💬 Discussion topic

Text Breakfast recipe is not appropriate

## ❗ Potential issues

Text seems more like lunch or dinner

## 👥 People to consult

@gitjl22
@g7lewis
@arontheising
@alejandravl
@msastry-code

## 📃 Details

Text

**Comment by g7lewis** [comment]
You never had breakfast fried rice?

**Comment by arontheising** [comment]
This issue has been resolved. We now have a recipe for scrambled eggs.
