### ISSUE TITLE
Lunch Recipe

### ISSUE THREAD

**Issue by alejandravl** [IntroToCode/Spring21_Recipes_Codemates7#14]
## 💬 Discussion topic

We don't have a menu for lunch

## ❗ Potential issues

We might go hungry without one!

## 👥 People to consult

Text

## 📃 Details

@gitjl22
@g7lewis
@arontheising
@alejandravl
@msastry-code

**Comment by arontheising** [comment]
This is a duplicate with #5 - closing this issue.
