### ISSUE TITLE
Lunch issue: Better cheese please

### ISSUE THREAD

**Issue by gitjl22** [IntroToCode/Spring21_Recipes_Codemates7#15]
## 💬 Discussion topic

I don't like cheddar cheese. Can we put swiss on the panini?

## ❗ Potential issues

Bigger issue: Is everyone good with dairy (vegan, lactose intolerance, etc.)?

## 👥 People to consult

@gitjl22
@g7lewis
@arontheising
@alejandravl
@msastry-code

## 📃 Details

I'd prefer to switch to swiss.

**Comment by msastry-code** [comment]
Just created a pull request and this has been approved! We are now onto swiss!
